### ISSUE TITLE
Recycle values in samplesFDistribution.R

### ISSUE THREAD

**Issue by choisant** [pglpm/bayes_nonparametric_inference#27]
Can you explain to me what this does and why? I will add the answers to the code.

**Comment by pglpm** [comment]
Recycling is a general feature of R, present in all its functions: see §2.2 in the [intro](http://cran.r-project.org/doc/manuals/R-intro.pdf) (or a text search on the whole manual). So it often appears naturally as a by-product when writing functions in R. This is the main reason.

It is also useful: for instance if we need the probability of several values of `Y` conditional on one particular value of `X` (as it happens when we want to plot `P(Y|X)` for Y), then thanks to recycling we only need to give one `Y` argument and a vector of `X` arguments. Vice versa too, if we need `P(Y|X)` for one specific value of `Y` and several conditional values of `X`. By recycling is also possible to build a grid of values to represent `P(X,Y)`. In base R functions this leads to fast computations because the operation is vectorized internally.

Unfortunately this built-in vectorization doesn't apply to `samplesFDistribution` – I didn't find a way to exploit R's built-in recycling capabilities for the actual computation there (which is performed in parallel by `foreach`). But an R user that builds scripts with R's characteristic recycling in mind would be happy that `samplesFDistribution` respects it.

(If this explains it, feel free to close the issue :) )

**Comment by pglpm** [comment]
Replaced by clearer `Pr()`, which creates a grid instead (more useful) in commit e029b32fcd40b6675888cb50ddac20a75ffecf10
