### ISSUE TITLE
Add timestamp in logs

### ISSUE THREAD

**Issue by choisant** [pglpm/bayes_nonparametric_inference#31]
This will be useful

**Comment by pglpm** [comment]
@choisant Added option `appendimestamp` to append a timestamp, and `appendinfo` to append information about the run (number of variates, number of datapoints, number of MC samples).

Since these options are clearly named `append...`, I think there's no need to change the argument `outputdir` to something with "suffix". Or? If you agree, feel free to close this issue :)

**Comment by pglpm** [comment]
Added recurring timestamps in the logs produced by inferpopulation.

**Comment by choisant** [comment]
@pglpm This is not what this issue was about. This is about adding a timestamp in the logs instead of just the elapsed time.

**Comment by pglpm** [comment]
@choisant Mmm... then I don't understand. You mean in the file name? The current update prints the current time recurrently within the log file.

**Comment by choisant** [comment]
Nevermind, I see it now:
```cat('\nCurrent time:',
            strftime(as.POSIXlt(Sys.time()), '%Y-%m-%d %H:%M:%S'))```
