### ISSUE TITLE
Try to put hyperparameters outside of inferpopulation

### ISSUE THREAD

**Issue by choisant** [pglpm/bayes_nonparametric_inference#32]
This is useful oviously

**Comment by pglpm** [comment]
The problem is that changing the hyperparameters would also require changing the pre-built functions `Qf` in `sysdata.rda`. So best to leave them in `inferpopulation`. 

Later on we can think of a way to give the user more control over the hyperprior – although at this point a user might just want to do their own custom Bayesian inference directly using Nimble?
